-- MySQL Script generated by MySQL Workbench
-- Tue Mar  9 18:12:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_smart_dental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_smart_dental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_smart_dental` DEFAULT CHARACTER SET utf8 ;
USE `bd_smart_dental` ;

-- -----------------------------------------------------
-- Table `bd_smart_dental`.`tbl_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_smart_dental`.`tbl_usuarios` (
  `idtbl_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasena` BIGINT(150) NULL,
  `rol` VARCHAR(45) NULL,
  `foto_perfil` VARCHAR(45) NULL,
  PRIMARY KEY (`idtbl_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_smart_dental`.`tbl_pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_smart_dental`.`tbl_pacientes` (
  `idtbl_pacientes` INT NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATE NULL,
  `genero` VARCHAR(45) NULL,
  `tipo_de_documento` VARCHAR(45) NULL,
  `documento` BIGINT(20) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` BIGINT(20) NULL,
  `direccion` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `zona` VARCHAR(45) NULL,
  `fecha_de_nacimiento` DATE NULL,
  `lugar_de_nacimiento` VARCHAR(45) NULL,
  `estado_civil` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `ocupacion` VARCHAR(45) NULL,
  `doctor_valoracion` VARCHAR(45) NULL,
  `doctor_tratante` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `eps_convenio` VARCHAR(45) NULL,
  `entero_de_nosotros` VARCHAR(45) NULL,
  `edad` INT(3) NULL,
  `nombre_acudiente` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idtbl_pacientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_smart_dental`.`tbl_proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_smart_dental`.`tbl_proveedores` (
  `idtbl_proveedores` INT NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATE NULL,
  `tipo_de_documento` VARCHAR(45) NULL,
  `documento` VARCHAR(45) NULL,
  `nombre_asesor` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `telefono_empresa` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `zona` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `codigo_CIIU` VARCHAR(45) NULL,
  `tipo_cuenta` VARCHAR(45) NULL,
  `banco` VARCHAR(45) NULL,
  `numero_cuenta` VARCHAR(45) NULL,
  PRIMARY KEY (`idtbl_proveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_smart_dental`.`tbl_cuentas_pendientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_smart_dental`.`tbl_cuentas_pendientes` (
  `idtbl_cuentas_por_pagar` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `numero_factura` VARCHAR(45) NULL,
  `fecha_factura` DATE NULL,
  `valor_factura` VARCHAR(45) NULL,
  `fecha_vencimiento` DATE NULL,
  `concepto_de_pago` VARCHAR(45) NULL,
  `responsable_de_pago` VARCHAR(45) NULL,
  `aprovada_por` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `tbl_proveedores_idtbl_proveedores` INT NOT NULL,
  PRIMARY KEY (`idtbl_cuentas_por_pagar`),
  INDEX `fk_tbl_cuentas_pendientes_tbl_proveedores_idx` (`tbl_proveedores_idtbl_proveedores` ASC),
  CONSTRAINT `fk_tbl_cuentas_pendientes_tbl_proveedores`
    FOREIGN KEY (`tbl_proveedores_idtbl_proveedores`)
    REFERENCES `bd_smart_dental`.`tbl_proveedores` (`idtbl_proveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
